<TestLayout>:

    BoxLayout:

        orientation: 'vertical'
        size_hint: None, None
        size: 100, 150
        pos_hint: {'center_x': .5, 'center_y': .5}

        Button:
            text: 'New Game'
            font_size: 12
            size: 100, 50

        Button:
            text: 'Hi-Scores'
            font_size: 12
            size: 100, 50

        Button:
            text: 'Settings'
            font_size: 12
            size: 100, 50